# Generated by Django 5.1.15 on 2026-02-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimCampaignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('year', models.SmallIntegerField(db_index=True)),
                ('quarter', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('week', models.SmallIntegerField()),
                ('day_of_week', models.SmallIntegerField()),
                ('day_of_month', models.SmallIntegerField()),
                ('day_of_year', models.SmallIntegerField()),
                ('is_weekend', models.BooleanField()),
                ('year_month', models.CharField(db_index=True, max_length=7)),
                ('year_week', models.CharField(db_index=True, max_length=8)),
                ('week_start', models.DateField()),
                ('month_start', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DimSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DimCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dashboard.dimbrand')),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dashboard.dimcampaigntype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='dashboard.dimsource')),
            ],
            options={
                'ordering': ['source', 'campaign_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dimbrand',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='dashboard.dimvertical'),
        ),
        migrations.AlterUniqueTogether(
            name='dimbrand',
            unique_together={('name', 'vertical')},
        ),
        migrations.CreateModel(
            name='FactBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mts_budget', models.DecimalField(decimal_places=4, help_text='Target MTS ratio (Cost ÷ Revenue), e.g. 0.2500', max_digits=6)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='dashboard.dimbrand')),
                ('month', models.ForeignKey(help_text='First-of-month row in DimDate', on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='dashboard.dimdate')),
            ],
            options={
                'unique_together': {('brand', 'month')},
            },
        ),
        migrations.CreateModel(
            name='FactMediaDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0)),
                ('impression_share', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000–1.0000; NULL when platform does not report', max_digits=5, null=True)),
                ('click_share', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.dimcampaign')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='dashboard.dimdate')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'campaign'], name='dashboard_f_date_id_b93fcf_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FactOrdersDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0)),
                ('new_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.dimbrand')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dashboard.dimdate')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'brand'], name='dashboard_f_date_id_e3fa72_idx')],
                'unique_together': {('brand', 'date')},
            },
        ),
    ]
