# Generated by Django 5.1.15 on 2026-02-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factbudget',
            name='cancellation_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Brand cancellation rate as a ratio, e.g. 0.0800 = 8%', max_digits=5),
        ),
    ]
