# Generated by Django 5.1.15 on 2026-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_factbudget_cancellation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='factbudget',
            name='manually_overridden',
            field=models.BooleanField(default=False, help_text='True if brand budget was manually edited (not auto-allocated).'),
        ),
    ]
