# Generated by Django 5.1.15 on 2026-02-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_factbudget_manually_overridden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimbrand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dimbrand',
            name='brand_id',
            field=models.IntegerField(blank=True, help_text='External brand identifier used in campaign naming convention', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dimbrand',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='dashboard.dimvertical'),
        ),
    ]
