# Generated by Django 5.1.15 on 2026-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dimbrand_unique_together_dimbrand_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimcampaign',
            name='amazon_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('sponsored', 'Sponsored Ads'), ('feed', 'Feed-based Listings')], default='', help_text='Amazon sub-type: Sponsored Ads or Feed-based Listings', max_length=20),
        ),
    ]
