# Generated by Django 5.1.15 on 2026-02-08 17:41

from django.db import migrations


def create_sources(apps, schema_editor):
    DimSource = apps.get_model("dashboard", "DimSource")
    for name, slug in [("Meta Ads", "meta-ads"), ("Amazon Marketplace", "amazon-marketplace")]:
        DimSource.objects.get_or_create(slug=slug, defaults={"name": name})


def remove_sources(apps, schema_editor):
    DimSource = apps.get_model("dashboard", "DimSource")
    DimSource.objects.filter(slug__in=["meta-ads", "amazon-marketplace"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dimcampaign_amazon_type'),
    ]

    operations = [
        migrations.RunPython(create_sources, remove_sources),
    ]
