# Generated by Django 5.1.15 on 2026-02-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_meta_amazon_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactVerticalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mts_budget', models.DecimalField(decimal_places=4, help_text='Target MTS ratio (Cost ÷ Revenue), e.g. 0.2500', max_digits=6)),
                ('cancellation_rate', models.DecimalField(decimal_places=4, default=0, help_text='Cancellation rate as a ratio, e.g. 0.0800 = 8%', max_digits=5)),
                ('month', models.ForeignKey(help_text='First-of-month row in DimDate', on_delete=django.db.models.deletion.PROTECT, related_name='vertical_budgets', to='dashboard.dimdate')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_budgets', to='dashboard.dimvertical')),
            ],
            options={
                'unique_together': {('vertical', 'month')},
            },
        ),
    ]
