# Generated by Django 5.1.15 on 2026-02-08 18:50

from django.db import migrations


def backfill(apps, schema_editor):
    """Populate FactVerticalBudget from existing FactBudget records.

    For each (vertical, month) with existing brand-level budgets, create a
    vertical-level record with:
      - revenue_budget = sum of brand revenue_budgets
      - mts_budget = taken from the first brand budget (uniform across brands)
      - cancellation_rate = taken from the first brand budget (uniform)
    """
    FactBudget = apps.get_model("dashboard", "FactBudget")
    FactVerticalBudget = apps.get_model("dashboard", "FactVerticalBudget")

    # Group existing brand budgets by (vertical_id, month_id)
    groups = {}
    for fb in FactBudget.objects.select_related("brand", "month").all():
        vertical_id = fb.brand.vertical_id
        if vertical_id is None:
            continue
        key = (vertical_id, fb.month_id)
        if key not in groups:
            groups[key] = {
                "revenue_total": fb.revenue_budget,
                "mts_budget": fb.mts_budget,
                "cancellation_rate": fb.cancellation_rate,
            }
        else:
            groups[key]["revenue_total"] += fb.revenue_budget

    for (vertical_id, month_id), vals in groups.items():
        FactVerticalBudget.objects.update_or_create(
            vertical_id=vertical_id,
            month_id=month_id,
            defaults={
                "revenue_budget": vals["revenue_total"],
                "mts_budget": vals["mts_budget"],
                "cancellation_rate": vals["cancellation_rate"],
            },
        )


def reverse(apps, schema_editor):
    apps.get_model("dashboard", "FactVerticalBudget").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_factverticalbudget'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse),
    ]
