# Generated by Django 5.1.15 on 2026-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_backfill_vertical_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimbrand',
            name='brand_id',
            field=models.IntegerField(blank=True, help_text='External brand identifier used in campaign naming convention', null=True),
        ),
        migrations.AddConstraint(
            model_name='dimbrand',
            constraint=models.UniqueConstraint(condition=models.Q(('brand_id__isnull', False)), fields=('brand_id', 'vertical'), name='unique_brand_id_per_vertical'),
        ),
    ]
