# Generated by Django 5.1.15 on 2026-02-09 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_brand_id_unique_per_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(unique=True)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='dashboard.dimvertical')),
            ],
            options={
                'ordering': ['site_id'],
            },
        ),
    ]
