# Generated by Django 5.1.15 on 2026-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dimsite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dimcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id', 'source'), name='unique_ext_id_per_source'),
        ),
    ]
