# Generated by Django 5.1.15 on 2026-02-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_unique_ext_id_per_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elasticity_window', models.PositiveSmallIntegerField(default=14)),
                ('efficiency_window', models.PositiveSmallIntegerField(default=28)),
                ('weight_a', models.PositiveSmallIntegerField(default=40)),
                ('weight_b', models.PositiveSmallIntegerField(default=30)),
                ('weight_c', models.PositiveSmallIntegerField(default=30)),
                ('min_click_threshold', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
