# Generated by Django 5.1.15 on 2026-02-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_scoringconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimcampaign',
            name='ad_group_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dimcampaign',
            name='matched_from',
            field=models.CharField(choices=[('campaign', 'Campaign Name'), ('ad_group', 'Ad Group Name'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
