# Generated by Django 5.1.15 on 2026-02-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_dimcampaign_ad_group_name_dimcampaign_matched_from'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='factmediadaily',
            name='dashboard_f_date_id_b93fcf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='factmediadaily',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='factmediadaily',
            name='ad_group_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='factmediadaily',
            unique_together={('campaign', 'date', 'ad_group_name')},
        ),
        migrations.AddIndex(
            model_name='factmediadaily',
            index=models.Index(fields=['date', 'campaign', 'ad_group_name'], name='dashboard_f_date_id_ac83d4_idx'),
        ),
    ]
