# Generated by Django 5.1.15 on 2026-02-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_factmediadaily_dashboard_f_date_id_b93fcf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary_statement', models.TextField(blank=True, default='')),
                ('major_yoy_shifts', models.TextField(blank=True, default='')),
                ('whats_working_well', models.TextField(blank=True, default='')),
                ('whats_needs_attention', models.TextField(blank=True, default='')),
                ('what_were_doing', models.TextField(blank=True, default='')),
                ('platform_testing', models.TextField(blank=True, default='')),
                ('channel_mix_observations', models.TextField(blank=True, default='')),
                ('risk_opportunity_outlook', models.TextField(blank=True, default='')),
                ('gm_discussion_points', models.TextField(blank=True, default='')),
                ('brand_notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='dashboard.dimvertical')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('vertical', 'week_start')},
            },
        ),
    ]
