# Generated by Django 5.1.15 on 2026-02-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_weeklyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('name', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='PromotionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_start', models.DateField()),
                ('cmp_end', models.DateField()),
                ('summary_statement', models.TextField(blank=True, default='')),
                ('major_yoy_shifts', models.TextField(blank=True, default='')),
                ('whats_working_well', models.TextField(blank=True, default='')),
                ('whats_needs_attention', models.TextField(blank=True, default='')),
                ('what_were_doing', models.TextField(blank=True, default='')),
                ('gm_discussion_points', models.TextField(blank=True, default='')),
                ('brand_notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_reports', to='dashboard.dimvertical')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.promotiondate')),
            ],
            options={
                'ordering': ['-promotion__start_date'],
                'unique_together': {('vertical', 'promotion')},
            },
        ),
    ]
